
package apsh.backend.serviceImpl.LegacySystemWebService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ERPService", targetNamespace = "http://service.legacy.apsh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ERPService {


    /**
     * 
     * @param arg0
     * @return
     *     returns apsh.backend.serviceImpl.LegacySystemWebService.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemByCode", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetItemByCode")
    @ResponseWrapper(localName = "getItemByCodeResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetItemByCodeResponse")
    public Item getItemByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<apsh.backend.serviceImpl.LegacySystemWebService.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductAll", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetProductAll")
    @ResponseWrapper(localName = "getProductAllResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetProductAllResponse")
    public List<Product> getProductAll();

    /**
     * 
     * @return
     *     returns java.util.List<apsh.backend.serviceImpl.LegacySystemWebService.Resource>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResourceAll", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetResourceAll")
    @ResponseWrapper(localName = "getResourceAllResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetResourceAllResponse")
    public List<Resource> getResourceAll();

    /**
     * 
     * @return
     *     returns java.util.List<apsh.backend.serviceImpl.LegacySystemWebService.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemAll", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetItemAll")
    @ResponseWrapper(localName = "getItemAllResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetItemAllResponse")
    public List<Item> getItemAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns apsh.backend.serviceImpl.LegacySystemWebService.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductByCode", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetProductByCode")
    @ResponseWrapper(localName = "getProductByCodeResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetProductByCodeResponse")
    public Product getProductByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns apsh.backend.serviceImpl.LegacySystemWebService.Resource
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResourceByCode", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetResourceByCode")
    @ResponseWrapper(localName = "getResourceByCodeResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "apsh.backend.serviceImpl.LegacySystemWebService.GetResourceByCodeResponse")
    public Resource getResourceByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
