# successful request
PUT {{hostAndPort}}/system-time/
Content-Type: application/json

{
  "startTime": "2017-06-11 12:00",
  "flowFactor": 2.0
}

###########

# get time set above
# {
#   "startTime": "2020-11-11 12:00",
#   "flowFactor": 2.0
# }
GET {{hostAndPort}}/system-time/

###########

# successful update
POST {{hostAndPort}}/system-time
Content-Type: application/json

{
  "startTime": "2017-06-10 12:00"
}

###########

# get time update above
# {
#   "startTime": "2020-11-10 12:00",
#   "flowFactor": 2.0
# }
GET {{hostAndPort}}/system-time/

###########

# failed request
PUT {{hostAndPort}}/system-time/
Content-Type: application/json

{
  "startTime": "2020-11-11 12:00"
}

###########

# failed update
POST {{hostAndPort}}/system-time
Content-Type: application/json

{}

###########

# get time update above
# {
#   "startTime": "2020-11-10 12:00",
#   "flowFactor": 2.0
# }
GET {{hostAndPort}}/system-time/
