language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  ssh_known_hosts: 123.57.73.97

cache:
  directories:
    - '$HOME/.m2/repository'

# 安装依赖前执行
before_install:

# 安装依赖
install:

# 执行构建脚本前执行
before_script:

# 执行构建脚本
script:
  - mvn clean install package -DskipTests=true
#  - docker build -t registry.cn-beijing.aliyuncs.com/chenpeihong/$APSH_BACKEND .
#  - echo -n 'YXBzaC1wZWlob25nY2hlbg==' | base64 --decode | docker login --username=876684433@qq.com --password-stdin registry.cn-beijing.aliyuncs.com
#  - docker push registry.cn-beijing.aliyuncs.com/chenpeihong/$APSH_BACKEND
#  - docker exit
  - echo -n 'Q2hwaDExNDk3NTQ4Mjk=' | base64 --decode | docker login --username=chph --password-stdin
  - docker build -t chph/$APSH_BACKEND .
  - docker push chph/$APSH_BACKEND
  - docker exit

# 构建脚本执行成功后执行
after_success:

# 构建脚本执行失败后执行
after_failure:

# 部署前执行
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# 部署
deploy:
  - scp ./kubernetes/*.yaml root@123.57.73.97:~/apsh/
  - ssh root@123.57.73.97 "kubectl apply -f ~/apsh"

# 部署完成后执行
after_deploy:

# 构建脚本完成后执行
after_script:

branches:
  only:
    - ci

notifications:
  email: false

# 设定环境变量
env:
  global:
    - GH_REF=https://github.com/APS-H/APS-Backend.git
    # apsh-backend镜像版本
    - APSH_BACKEND=apsh-backend:v1-alpha