spring:
  datasource:
    url: jdbc:mysql://123.57.73.97:30306/apsh_test?createDatabaseIfNotExist=true
    username: root
    password: 123456

optaplanner:
  solver:
    termination:
      spent-limit: 5s