spring:
  profiles:
    active: @profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: "*"
time-server:
  start-time: /usr/local/apsh-ts-start  # 系统起始时间
  time-speed: /usr/local/apsh-ts-speed  # 时间流动系数

