spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/apsh?createDatabaseIfNotExist=true
    username: root
    password: 123456

time-server-url: /tmp/.apsh-backend/apsh-ts  # 系统起始时间 和 时间流动系数

optaplanner:
  solver:
    termination:
      spent-limit: 10h
      best-score-limit: 0hard/*soft