spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apsh_test?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

optaplanner:
  solver:
    termination:
      spent-limit: 5s