spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apsh_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

time-server-url: /tmp/.apsh-backend/apsh-ts  # 系统起始时间 和 时间流动系数

optaplanner:
  solver:
    termination:
      spent-limit: 20s