package apsh.backend.serviceimpl.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ERPServiceService", targetNamespace = "http://service.legacy.apsh.com/", wsdlLocation = "http://81.69.252.233:9003/erp?wsdl")
public class ERPServiceService
        extends Service {

    private final static URL ERPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ERPSERVICESERVICE_EXCEPTION;
    private final static QName ERPSERVICESERVICE_QNAME = new QName("http://service.legacy.apsh.com/", "ERPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://81.69.252.233:9003/erp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPSERVICESERVICE_WSDL_LOCATION = url;
        ERPSERVICESERVICE_EXCEPTION = e;
    }

    public ERPServiceService() {
        super(__getWsdlLocation(), ERPSERVICESERVICE_QNAME);
    }

    public ERPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPSERVICESERVICE_QNAME, features);
    }

    public ERPServiceService(URL wsdlLocation) {
        super(wsdlLocation, ERPSERVICESERVICE_QNAME);
    }

    public ERPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPSERVICESERVICE_QNAME, features);
    }

    public ERPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ERPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ERPService
     */
    @WebEndpoint(name = "ERPServicePort")
    public ERPService getERPServicePort() {
        return super.getPort(new QName("http://service.legacy.apsh.com/", "ERPServicePort"), ERPService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ERPService
     */
    @WebEndpoint(name = "ERPServicePort")
    public ERPService getERPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.legacy.apsh.com/", "ERPServicePort"), ERPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPSERVICESERVICE_EXCEPTION != null) {
            throw ERPSERVICESERVICE_EXCEPTION;
        }
        return ERPSERVICESERVICE_WSDL_LOCATION;
    }

}
